### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(MiniTermProject)
add_subdirectory(QuickQanava)
add_subdirectory(MiniTermProjectContent)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
	MiniTermProjectplugin
	QuickContainersplugin
	MiniTermProjectContentplugin)